services:
  server:
    build: .
    ports:
      - "443:443"
      - "80:80"
    develop:
      watch:
        - action: rebuild
          path: src
          initial_sync: true
        - action: sync
          path: public
          target: /app/public
          initial_sync: true
        - action: sync
          path: assets
          target: /app/assets
          initial_sync: true
