services:
  server:
    build: .
    ports:
      - "443:443"
      - "80:80"
    develop:
      watch:
        - action: rebuild
          path: src
          initial_sync: true
        - action: sync
          path: pages
          target: /app/pages
          initial_sync: true
